# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ozcFuqxr-y3z8f5dJRtWpsnetHEDNID
"""

a=int (input("enter a number"))
b=int(input("enter a number"))
c=a+b
print(c)

"""addition of two number"""